- Python 3.x
- Hanseo Jo

In [2]:
# Problem 1

import numpy as np

a=np.eye(2)
b=np.concatenate([a,a]*2,axis=0)
print(np.concatenate([b,b]*2,axis=1))

[[ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]]


In [66]:
# Problem 2

A=np.array([[1,2,3],[4,5,6]])
print(A.reshape((1,6))[0][4])

5


In [68]:
# Problem 3

A=[[1,2,3],[4,5,6]]
B=[[7,8,9],[10,11,12]]

np.concatenate([A,B],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
# Problem 4

x=np.arange(1,4)[:,np.newaxis]
y=np.arange(4,7)[:,np.newaxis]
np.concatenate([x,y],axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
# Problem 5

x=np.eye(4)
x=(x.argsort(0)).argsort(0)
rank=0
o=np.zeros(4, dtype=int)

for i in range(4):
    if(not(x[i]==o).all()):
        rank+=1
print(rank)

4
