- Python 3.x
- Hanseo Jo

In [41]:
#pwd

'C:\\Users\\hanseo'

In [39]:
#%%writefile -a test.py 
#print("hello, world!")

# magic command

Appending to test.py


In [30]:
#run test.py

hello, world!


In [52]:
# Problem 1

import numpy as np

np.random.seed(0)
x=np.random.rand(5,5)

for i in range(5):
    for j in range(5):
        x[j][i]=(x[j][i]-min(x[:,i]))/(max(x[:,i])-min(x[:,i]))
print(x)

[[ 0.51787984  0.89220071  0.32834325  0.          0.44133829]
 [ 0.62677698  0.47864367  1.          1.          0.39100727]
 [ 0.79035827  0.58335647  0.35688067  0.92559664  0.        ]
 [ 0.          0.          0.7507951   0.77815675  1.        ]
 [ 1.          0.89571613  0.19822046  0.78052918  0.11827443]]


In [9]:
# Problem 2

import numpy as np

np.random.seed(10)
quiz2Arr=np.random.randint(0,10,(4,4))

a=[1,2,3,0]
qq=quiz2Arr[a]
qq=[list(qq[x]) for x in range(4)]
print(qq)

[[9, 0, 1, 8], [9, 0, 8, 6], [4, 3, 0, 4], [9, 4, 0, 1]]


In [46]:
# Problem 3

import numpy as np

np.random.seed(100)
quiz3Arr = np.random.uniform(0,1,10)
num = 0.5
print(quiz3Arr)
min(abs(quiz3Arr-num))+num

[ 0.54340494  0.27836939  0.42451759  0.84477613  0.00471886  0.12156912
  0.67074908  0.82585276  0.13670659  0.57509333]


0.54340494179096543

In [100]:
# Problem 4

import numpy as np

x=np.array([1,3,0,-1,-3])

def sign(x):
    a=x<0
    return [1 if a[i]==False else -1 for i in range(len(a))]
sign(x)

[1, 1, 1, -1, -1]

In [77]:
# Problem 5

import numpy as np
import pandas as pd

data={'animal':['cat','cat','snake','dog','dog','cat','snake','cat','dog','dog'],
      'age':[2.5,3,0.5,np.nan,5,2,4.5,np.nan,7,3],
      'visits':[1,3,2,3,2,3,1,1,2,1],
      'priority':['yes','yes','no','yes','no','no','no','yes','no','no']
     }
labels=['a','b','c','d','e','f','g','h','i','j']

pd.DataFrame(data,index=labels).loc[:,:'priority']

age animal priority
a  2.5    cat      yes
b  3.0    cat      yes
c  0.5  snake       no
d  NaN    dog      yes
e  5.0    dog       no
f  2.0    cat       no
g  4.5  snake       no
h  NaN    cat      yes
i  7.0    dog       no
j  3.0    dog       no