In [3]:
import numpy as np
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [3]:
# array is method that creates ndarray
# ndarray is object and it is also method that is used more in row level

In [4]:
fl32_arr=np.array([1,2,3,4],dtype='float32')
[type(elem) for elem in fl32_arr]

[numpy.float32, numpy.float32, numpy.float32, numpy.float32]

In [6]:
np.array([[2,3,4],[4,5,6],[6,7,8]]) # the view is not a line shape.

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones((3,5),dtype='float')

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [13]:
np.full((3,5),3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [14]:
np.arange(0,20,2) # array range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [21]:
np.random.random((3,3)) # uniform distribution

array([[ 0.88162194,  0.70373372,  0.56895924],
       [ 0.59294682,  0.05858306,  0.43421506],
       [ 0.27078218,  0.50886253,  0.14551537]])

In [23]:
np.random.normal(0,1,(3,3)) # nomal distribution, avr=0, 분산 =1

array([[ 0.77445355,  1.21888189, -0.89641101],
       [-0.20490465, -0.16378409,  0.34335695],
       [-0.76839629, -1.07236504,  1.10250601]])

In [24]:
np.random.randint(0,10,(3,3)) 

array([[1, 5, 2],
       [6, 7, 6],
       [6, 8, 8]])

In [73]:
A=np.zeros((10,10),int)
A[:,0::9]=1
A[0::9,:]=1
A

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [4]:
np.random.seed(10)
x2=np.random.randint(10,size=(2,4,5))
x2

array([[[9, 4, 0, 1, 9],
        [0, 1, 8, 9, 0],
        [8, 6, 4, 3, 0],
        [4, 6, 8, 1, 8]],

       [[4, 1, 3, 6, 5],
        [3, 9, 6, 9, 1],
        [9, 4, 2, 6, 7],
        [8, 8, 9, 2, 0]]])

In [50]:
print(x2.ndim)
print(x2.shape)
print(x2.size) # the number of attributes

3
(2, 4, 5)
40


In [5]:
print(x2[1][:][1]) #? approch as array
print(x2[1][1]) #? approch as array 
print(x2[1,:,1]) # approch as matrix

[3 9 6 9 1]
[3 9 6 9 1]
[1 9 4 8]


In [6]:
x=np.arange(10)
print(x[-1::-2])
print(x[9::-2])

[9 7 5 3 1]
[9 7 5 3 1]


In [10]:
# numpy array sliceing gives 'View'

aa = np.random.randint(10, size=(4,5))
print(aa)
aa_sub=aa[:2,:2]
print(aa_sub)
aa_sub[0][0]=1
print(aa)

[[0 4 2 0 3]
 [3 1 2 5 9]
 [0 1 0 1 9]
 [0 9 2 1 1]]
[[0 4]
 [3 1]]
[[1 4 2 0 3]
 [3 1 2 5 9]
 [0 1 0 1 9]
 [0 9 2 1 1]]


In [14]:
# So, it is good to use 'copy()'

aa_copy=aa[:2,:2].copy()
aa_copy[0][0]=100
print(aa_copy)
print(aa)

[[100   4]
 [  3   1]]
[[1 4 2 0 3]
 [3 1 2 5 9]
 [0 1 0 1 9]
 [0 9 2 1 1]]


In [15]:
gird_before=np.arange(1,10)
gird_before.shape # dimension is 1

(9,)

In [17]:
x=np.array([1,2,3,4,5])
print(x) # 1 dimension array
print(x[np.newaxis,:]) # 2 dimension row matrix
print(x[:,np.newaxis]) # 2 dimension column matrix

[1 2 3 4 5]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [18]:
x=np.array([1,2,3])
y=np.array([3,2,1])
print(np.concatenate([x,y]))
np.concatenate(x,y) # use []

[1 2 3 3 2 1]


TypeError: only length-1 arrays can be converted to Python scalars

In [21]:
gird=np.array([[1,2,3,],[4,5,6]])
gird

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
print(np.concatenate([gird,gird],axis=0))
print(np.concatenate([gird,gird],axis=1))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [24]:
print(np.vstack([gird,gird]))
print(np.hstack([gird,gird]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [98]:
x=[1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [99]:
grid=np.arange(16).reshape((4,4))
upper, lower = np.vsplit(grid,[2])
print(grid)
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [100]:
print(np.arange(5))
display(np.arange(5))

[0 1 2 3 4]


array([0, 1, 2, 3, 4])

In [102]:
x=np.arange(4)
display(x+1)
np.add(x,1)

array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [103]:
x=np.array([-2,1])
print(abs(x))
print(np.absolute(x))
print(np.abs(x))

[2 1]
[2 1]
[2 1]


In [27]:
x=np.arange(5)
y=np.empty(5)
display(y)
np.multiply(x,10,out=y) # use of 'out'
display(y)

array([ 0.,  0.,  0.,  0.,  0.])

array([  0.,  10.,  20.,  30.,  40.])

In [106]:
y=np.zeros(10)
np.power(2,x,out=y[::2])
display(y)

array([  1.,   0.,   2.,   0.,   4.,   0.,   8.,   0.,  16.,   0.])

In [107]:
x=np.arange(1,6)
np.add.reduce(x) # reduce : return one scalar value

15

In [109]:
a=np.add.accumulate(x) # accmulate : it remains original shape
a

array([ 1,  3,  6, 10, 15], dtype=int32)

In [110]:
np.multiply.outer(x,x) # outer product(correlation)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [28]:
A=np.ones(3)*1
B=np.ones(3)*2
np.add(A,B,out=B)
np.multiply(-1/2,A,out=A)
np.multiply(A,B,out=B)
print(A)
print(B)

[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


In [30]:
a=np.arange(3) # (3,) -> 1차원
b=np.arange(1,4)[:,np.newaxis] #(3,1) -> 2차원
print(a)
print(b)
print(a+b)
print(b+a)

[0 1 2]
[[1]
 [2]
 [3]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [31]:
print ( round(3.123456, 4) )

3.1235
